# /etc/nginx/sites-available/asc26.sympoietic.systems

server {
    listen 80;
    listen [::]:80;
    server_name asc26.sympoietic.systems;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name asc26.sympoietic.systems;

    ssl_certificate /etc/letsencrypt/live/asc26.sympoietic.systems/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/asc26.sympoietic.systems/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 50M;

    location / {
        proxy_pass http://127.0.0.1:8742;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
